# USERS
###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Jonathan",
  "lastName": "Mambrin",
  "age": 80,
  "address": "Av. Siempre Viva"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/6137e2bb2e329eb206b0073e HTTP/1.1

###
DELETE http://localhost:9000/api/users/63af2fef4103807a4bafb844 HTTP/1.1

###
PUT http://localhost:9000/api/users/6137e2412e329eb206b0073c HTTP/1.1
Content-Type: application/json

{
  "name": "Jonathan",
  "lastName": "Mambrin",
  "age": 80,
  "address": "Av. Siempre Viva"
}

---------------------------------------------------------------------------------------------------------
#ROLES
###
POST http://localhost:9000/api/roles HTTP/1.1
Content-Type: application/json

{
  "name": "John Conway",
  "description": "No"
}

###
GET http://localhost:9000/api/roles HTTP/1.1

###
GET http://localhost:9000/api/roles/6137e2bb2e329eb206b0073e HTTP/1.1

###
DELETE http://localhost:9000/api/roles/63af2fef4103807a4bafb844 HTTP/1.1

###
PUT http://localhost:9000/api/roles/6137e2412e329eb206b0073c HTTP/1.1
Content-Type: application/json

{
  "name": "John Conway",
  "description": "No"
}


---------------------------------------------------------------------------------------------------------
#TASKS
###
POST http://localhost:9000/api/tasks HTTP/1.1
Content-Type: application/json

{
  "name": "John Conwayq",
  "description": "No"
}

###
GET http://localhost:9000/api/tasks HTTP/1.1

###
GET http://localhost:9000/api/tasks/6137e2bb2e329eb206b0073e HTTP/1.1

###
DELETE http://localhost:9000/api/tasks/63af2fef4103807a4bafb844 HTTP/1.1

###
PUT http://localhost:9000/api/tasks/6137e2412e329eb206b0073c HTTP/1.1
Content-Type: application/json

{
  "name": "John Conway",
  "description": "No"
}